name: expenses
description: "A new Flutter project."
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  # ios style icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting rules for Flutter apps, packages, and plugins
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true